onEvent('item.registry', e => {
	e.create('ragnamod_seven:portal_activator').displayName('传送门激活器').maxStackSize(1);
	e.create('chickens:smashed_chicken').displayName('被压扁的坤饼');
	e.create('chickens:chicken_skin').displayName('坤哥的皮');
	e.create('chickens:chicken_shell').displayName('坤哥的壳');
	e.create('chickens:nether_star_shard').displayName('§e下界之星碎片').glow(true);
	e.create('chickens:soul_chicken').displayName('坤魂').glow(true);
	e.create('chemlib:draconium_compound').displayName('龙复合物');
	e.create('ragnamod_seven:infinity_gem').displayName('§c无尽宝石');
	e.create('ragnamod_seven:infinity_gear').displayName('§c无尽齿轮');
	e.create('ragnamod_seven:sphere').displayName('万物之球');
	e.create('ragnamod_seven:ignis_soul').displayName('焰魔灵魂');
	e.create('ragnamod_seven:revenant_soul').displayName('燃魂灵魂');
	e.create('ragnamod_seven:netherite_monstrosity_soul').displayName('下界合金巨兽灵魂');
	e.create('ragnamod_seven:ender_golem_soul').displayName('末影傀儡灵魂');
	e.create('ragnamod_seven:ender_guardian_soul').displayName('末影守卫灵魂');
	e.create('ragnamod_seven:log_egg_component').displayName('原木坤精华');
	e.create('gateways:catalyst_small_pearl_gate').displayName('小型门催化剂');
	e.create('gateways:catalyst_medium_pearl_gate').displayName('中型门催化剂');
	e.create('gateways:catalyst_large_pearl_gate').displayName('大型型门催化剂');
	e.create('solarflux:photovoltaic_cell_7').displayName('光伏电池 VII');
	e.create('solarflux:photovoltaic_cell_8').displayName('光伏电池 VIII');
	e.create('solarflux:photovoltaic_cell_9').displayName('光伏电池 XI');
	e.create('solarflux:photovoltaic_cell_10').displayName('光伏电池 X');
	e.create('solarflux:photovoltaic_cell_11').displayName('光伏电池 XI');
	e.create('solarflux:photovoltaic_cell_12').displayName('光伏电池 XII');
	e.create('solarflux:photovoltaic_cell_13').displayName('光伏电池 XIII');
	e.create('hostilenetworks:blueskies_prediction').displayName('通用蔚蓝浩空预测产物');
	e.create('hostilenetworks:undergarden_prediction').displayName('通用深暗之园预测产物');
	e.create('hostilenetworks:twilight_prediction').displayName('通用暮色森林预测产物');
	e.create('hostilenetworks:polymer_clay').displayName('聚合粘土');
	e.create('ragnamod_seven:war_essence').displayName('战争精华');
	e.create('ragnamod_seven:famine_essence').displayName('饥荒精华');
	e.create('ragnamod_seven:death_essence').displayName('死亡精华');
	e.create('ragnamod_seven:conquest_essence').displayName('征服精华');
	e.create('ragnamod_seven:war_essence_materialized').displayName('物质化的战争精华');
	e.create('ragnamod_seven:famine_essence_materialized').displayName('物质化的饥荒精华');
	e.create('ragnamod_seven:death_essence_materialized').displayName('物质化的死亡精华');
	e.create('ragnamod_seven:conquest_essence_materialized').displayName('物质化的征服精华');
	e.create('ragnamod_seven:war_ingot').displayName('战争锭');
	e.create('ragnamod_seven:famine_ingot').displayName('饥荒锭');
	e.create('ragnamod_seven:death_ingot').displayName('死亡锭');
	e.create('ragnamod_seven:conquest_ingot').displayName('征服锭');
	e.create('ragnamod_seven:war_nugget').displayName('战争粒');
	e.create('ragnamod_seven:famine_nugget').displayName('饥荒粒');
	e.create('ragnamod_seven:death_nugget').displayName('死亡粒');
	e.create('ragnamod_seven:conquest_nugget').displayName('征服粒');
	e.create('ragnamod_seven:sculk_ingot').displayName('幽匿锭');
	e.create('ragnamod_seven:shub_niggurath_ingot').displayName('尼古拉丝锭');
	e.create('ragnamod_seven:unknown_ingot').displayName('未知锭');
	e.create('ragnamod_seven:unknown_nugget').displayName('未知粒');
	e.create('ragnamod_seven:raw_unknown').displayName('粗未知');
	e.create('ragnamod_seven:chemical_core').displayName('化学核心').glow(true);
	e.create('ragnamod_seven:ghast_cow_tear').displayName('恶魂牛之泪');
	e.create('ragnamod_seven:ghast_cow_star').displayName('恶魂牛之星').glow(true);
	e.create('ragnamod_seven:chemical_draconium_ingot').displayName('化学龙锭');
	e.create('ragnamod_seven:chemical_draconium_nugget').displayName('化学龙粒');
	e.create('ragnamod_seven:condensed_ingot').displayName('浓缩锭');
	e.create('ragnamod_seven:black_sphere').displayName('非物品').maxStackSize(1);
	e.create('miniutilities:stable_ingot').displayName('稳定金属锭');
	e.create('ragnamod_seven:agglomerate_matter_minecraft1').displayName('§b原版聚合物质 #1');
	e.create('ragnamod_seven:agglomerate_matter_minecraft2').displayName('§b原版聚合物质 #2');
	e.create('ragnamod_seven:agglomerate_matter_minecraft3').displayName('§b原版聚合物质 #3');
	e.create('ragnamod_seven:agglomerate_matter_twilight').displayName('§b 暮色聚合物质');
	e.create('ragnamod_seven:agglomerate_matter_blood_magic').displayName('§b血魔法聚合物质');
	e.create('ragnamod_seven:agglomerate_matter_create').displayName('§b机械动力聚合物质');
	e.create('ragnamod_seven:agglomerate_matter_mekanism').displayName('§b通用机械聚合物质');
	e.create('ragnamod_seven:agglomerate_matter_powah').displayName('§bPowah聚合物质');
	e.create('ragnamod_seven:agglomerate_matter_botania').displayName('§b植物魔法聚合物质');
	e.create('ragnamod_seven:agglomerate_matter_blue_skies').displayName('§b蔚蓝浩空聚合物质');
	e.create('ragnamod_seven:agglomerate_matter_space').displayName('§b飞越地球聚合物质');
	e.create('ragnamod_seven:agglomerate_matter_blocky').displayName('§b建筑师聚合物质');
	e.create('ragnamod_seven:agglomerate_matter_mobs').displayName('§b圣遗物聚合物质');
	e.create('ragnamod_seven:agglomerate_matter_psi').displayName('§bPSI聚合物质');
	e.create('ragnamod_seven:agglomerate_matter_thermal').displayName('§b热力聚合物质');
	e.create('ragnamod_seven:agglomerate_matter_evil_craft').displayName('§b邪恶工艺聚合物质');
	e.create('ragnamod_seven:agglomerate_matter_ae2').displayName('§bAE2聚合物质');
	e.create('ragnamod_seven:agglomerate_matter_forbidden_arcanus').displayName('§b禁忌聚合物质');
	e.create('ragnamod_seven:agglomerate_matter_undergarden').displayName('§b深谙之园聚合物质');
	e.create('ragnamod_seven:agglomerate_matter_ftbic').displayName('§bFTB工业聚合物质');
	e.create('ragnamod_seven:agglomerate_matter_tconstruct').displayName('§b匠魂聚合物质');
	e.create('ragnamod_seven:agglomerate_matter_ars').displayName('§b新生魔艺聚合物质');
	e.create('ragnamod_seven:agglomerate_matter_pneumaticcraft').displayName('§b气动工艺聚合物质');
	e.create('ragnamod_seven:agglomerate_matter_tech').displayName('§b科技聚合物质');
	e.create('ragnamod_seven:creative_augment_base').displayName('创造升级基板');
	e.create('ragnamod_seven:holy_powders').displayName('神圣魔法粉末');
	e.create('ragnamod_seven:creative_tc_crystal')
		.displayName('创造匠魂水晶')
		.glow(true)
		.maxStackSize(1);
	e.create('ragnamod_seven:alloy_matrix').displayName('§c矩阵合金').glow(true).maxStackSize(1);
	e.create('ragnamod_seven:solid_nuclear_waste').displayName("固态核废料")
	e.create('thermal:press_rod_die').displayName("棒杆模具")
    e.create('thermal:press_wire_die').displayName("线材模具")
});
